-- ==========================================================
-- DDL
-- ==========================================================
/*
    NOMBRES: 
            - VALERIA MUÑOZ GUERRERO
            - NICOLE BURBANO SOLARTE
            - JUAN CAMILO HENAO VILLEGAS
            - JUAN PABLO COLLAZOS SAMBONI
            - JESUS EDUARDO LASSO MUÑOZ
*/

-- ===============================
-- DROP TABLES
-- ===============================
DROP TABLE IF EXISTS inv_movement CASCADE;
DROP TABLE IF EXISTS bill CASCADE;
DROP TABLE IF EXISTS order_detail CASCADE;
DROP TABLE IF EXISTS "ORDER" CASCADE;
DROP TABLE IF EXISTS client_detail CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS product_type CASCADE;
DROP TABLE IF EXISTS provider CASCADE;
DROP TABLE IF EXISTS cities CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS cart CASCADE;

-- ===============================
-- BASE TABLES
-- ===============================

CREATE TABLE product_type (
    type_code INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(100) NOT NULL
);

CREATE TABLE product (
    pro_code INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_name VARCHAR(100) NOT NULL,
    pro_img VARCHAR(500),
    pro_price NUMERIC(15,2) NOT NULL CHECK (pro_price > 0),
    pro_type INTEGER NOT NULL,
    descript VARCHAR(1000),
    pro_mark VARCHAR(100) NOT NULL,
    pro_status CHAR(1) DEFAULT 'A' CHECK (pro_status IN ('A','I')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_type
        FOREIGN KEY (pro_type)
        REFERENCES product_type(type_code)
        ON DELETE RESTRICT
);

CREATE TABLE provider (
    prov_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prov_email VARCHAR(80) NOT NULL UNIQUE,
    prov_name VARCHAR(80) NOT NULL,
    prov_phone VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE inventory (
    inv_code INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_code INTEGER NOT NULL,
    inv_stock INTEGER NOT NULL CHECK (inv_stock >= 0),
    selling_price NUMERIC(15,2) NOT NULL CHECK (selling_price > 0),
    inv_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    inv_prov INTEGER NOT NULL,
    inv_status CHAR(1) DEFAULT 'A' CHECK (inv_status IN ('A','I')),

    CONSTRAINT fk_inventory_product
        FOREIGN KEY (pro_code)
        REFERENCES product(pro_code)
        ON DELETE CASCADE,

    CONSTRAINT fk_inventory_provider
        FOREIGN KEY (inv_prov)
        REFERENCES provider(prov_id)
        ON DELETE RESTRICT
);

CREATE TABLE departments (
    dep_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dep_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE cities (
    city_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name VARCHAR(100) NOT NULL,
    dep_id INTEGER NOT NULL,

    CONSTRAINT fk_city_department
        FOREIGN KEY (dep_id)
        REFERENCES departments(dep_id)
        ON DELETE CASCADE
);

CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(30) NOT NULL UNIQUE,
    user_password VARCHAR(255) NOT NULL,
    user_email VARCHAR(80) NOT NULL UNIQUE,
    user_role VARCHAR(20) DEFAULT 'CLIENT'
        CHECK (user_role IN ('ADMIN', 'CLIENT')),
    user_phone VARCHAR(20),
    status CHAR(1) DEFAULT 'A' CHECK (status IN ('A','I')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE client_detail (
    user_id INTEGER PRIMARY KEY,
    first_name VARCHAR(25) NOT NULL,
    second_name VARCHAR(25),
    first_last_name VARCHAR(25) NOT NULL,
    second_last_name VARCHAR(25),
    address VARCHAR(100) NOT NULL,
    desc_address VARCHAR(200),
    city_id INTEGER NOT NULL,
    dep_id INTEGER NOT NULL,

    CONSTRAINT fk_client_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_client_city
        FOREIGN KEY (city_id)
        REFERENCES cities(city_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_client_dep
        FOREIGN KEY (dep_id)
        REFERENCES departments(dep_id)
        ON DELETE RESTRICT
);

CREATE TABLE "ORDER" (
    ord_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ord_state VARCHAR(30) NOT NULL CHECK (
        ord_state IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled')
    ),
    ord_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER NOT NULL,

    CONSTRAINT fk_order_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

CREATE TABLE order_detail (
    ord_id INTEGER NOT NULL,
    pro_code INTEGER NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(15,2) NOT NULL CHECK (unit_price > 0),

    PRIMARY KEY (ord_id, pro_code),

    CONSTRAINT fk_detail_order
        FOREIGN KEY (ord_id)
        REFERENCES "ORDER"(ord_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_detail_product
        FOREIGN KEY (pro_code)
        REFERENCES product(pro_code)
        ON DELETE RESTRICT
);

CREATE TABLE bill (
    bill_code INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_code INTEGER NOT NULL,
    ord_id INTEGER NOT NULL,
    payment_type VARCHAR(40) NOT NULL CHECK (
        payment_type IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA')
    ),
    bill_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_bill NUMERIC(15,2) NOT NULL CHECK (total_bill > 0),

    CONSTRAINT fk_bill_inventory
        FOREIGN KEY (inv_code)
        REFERENCES inventory(inv_code)
        ON DELETE RESTRICT,

    CONSTRAINT fk_bill_order
        FOREIGN KEY (ord_id)
        REFERENCES "ORDER"(ord_id)
        ON DELETE CASCADE
);

CREATE TABLE inv_movement (
    inv_mov_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_code INTEGER NOT NULL,
    mov_type VARCHAR(20) NOT NULL CHECK (
        mov_type IN ('ENTRADA', 'SALIDA', 'DEVOLUCION', 'AJUSTE')
    ),
    mov_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    prev_stock INTEGER,
    new_stock INTEGER,
    reason VARCHAR(200),
    ord_id INTEGER,
    user_id INTEGER,

    CONSTRAINT fk_mov_inventory
        FOREIGN KEY (inv_code)
        REFERENCES inventory(inv_code)
        ON DELETE CASCADE,

    CONSTRAINT fk_mov_order
        FOREIGN KEY (ord_id)
        REFERENCES "ORDER"(ord_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_mov_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE SET NULL
);

CREATE TABLE cart (
    cart_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    pro_code INTEGER NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    added_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_cart_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_cart_product
        FOREIGN KEY (pro_code)
        REFERENCES product(pro_code)
        ON DELETE CASCADE,

    CONSTRAINT uq_cart UNIQUE (user_id, pro_code)
);